### ISSUE TITLE
Exception on some scores

### ISSUE THREAD

**Issue by me0wday** [pidgy/unitehud#3]
Just wanted to say this is a very interesting project, I am having trouble debugging the cause of a crash that seems to happen consistently on certain scores (eg. +50 to orange).

Error:
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) ./modules/core/src/matrix.cpp:810: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function `'Mat'

SIGABRT: abort
PC=0x7fdc0fb10891 m=10 sigcode=18446744073709551610
signal arrived during cgo execution
```

I have determined the responsible code to be: Line 27 in `match.go`. When matrix.Region( is called.

The X and Y of the Point at the time is X=700, Y=285.

I hope this helps.
P.S. Can provide a snapshot at the time too.

**Comment by pidgy** [comment]
Thanks for raising this issue @me0wday 

I am aware of this issue, caused by the image comparison call to match template having invalid image sizes (trying to search wider images in a smaller space) 

If you would like to reach out to me on discord @ pidgy # 0069 I would love to see any snapshots you have.

**Comment by pidgy** [comment]
issues are resolved
